name: Keep Render Alive

on:
  schedule:
    - cron: "*/5 * * * *"  

jobs:
  keep_alive:
    runs-on: ubuntu-latest
    env:
      BACKEND_URL: ${{ secrets.RENDER_BACKEND_URL }}  # Get the URL from GitHub Secrets

    steps:
      - name: Ping Render Backend
        run: curl -s "$BACKEND_URL/healthz"
