name: Keep Render Alive

on:
  schedule:
    - cron: "*/10 * * * *"  # Runs every 10 minutes

jobs:
  keep_alive:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render Backend
        run: curl -s "https://jsbackend-47kc.onrender.com/healthz"
